export const REGIONS = {
  India: {
    country: 'India',
    code: 'IN',
    currency: 'INR',
    phoneCode: '+91',
    postalLabel: 'PIN Code',
    postalPlaceholder: 'e.g. 400001',
    states: [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
      'Delhi (NCT)',
      'Jammu & Kashmir',
      'Ladakh',
      'Puducherry',
      'Chandigarh',
      'Dadra & Nagar Haveli and Daman & Diu',
      'Andaman & Nicobar Islands',
      'Lakshadweep',
    ],
  },
  Nepal: {
    country: 'Nepal',
    code: 'NP',
    currency: 'NPR',
    phoneCode: '+977',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 44600',
    states: [
      'Koshi Province (Province 1)',
      'Madhesh Province (Province 2)',
      'Bagmati Province (Province 3)',
      'Gandaki Province (Province 4)',
      'Lumbini Province (Province 5)',
      'Karnali Province (Province 6)',
      'Sudurpashchim Province (Province 7)',
    ],
  },
} as const;

export type SupportedCountry = keyof typeof REGIONS;
